### ISSUE TITLE
模板消息 data里有中文会导致发送不成功

### ISSUE THREAD

**Issue by raighnew** [progrape/tmsg#1]
data中有中文时发送错误{ errcode: 47001,
  errmsg: 'data format error hint: [cKsgba0547ge20]' }

但是把json复制到postman里发送又能成功

**Comment by ngxiaoyi** [comment]
为什么要关了，貌似issue还在啊

**Comment by raighnew** [comment]
作者已经不维护了，我修复了，https://github.com/raighneweng/tmsg
